add: 마이페이지 유저정보 불러오기 기능 구현
wecode-bootcamp-korea/27-1st-branch-backend pull request #12
Opened 2021-12-02 06:41 UTC by whytili89

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 마이페이지에 나올 유저정보 불러오기

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 유저아이디를 통해 유저정보 불러오기 기능
2. 유저정보 불러올 때 일어날 수 있는 오류 정의 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2021-12-02 06:52 UTC, bigfanoftim commented
csv 파일들이 불필요하게 올라왔네요 지워주세요~

2021-12-02 07:00 UTC, bigfanoftim requested changes

2021-12-02 07:00 UTC, bigfanoftim commented on users/views.py
> +                raise User.DoesNotExist()
해당 에러에 대해서 팀원들과 함께 이야기해서 raise가 왜 필요한지 다시 한 번 생각해주세요!

2021-12-02 07:00 UTC, bigfanoftim commented on users/views.py
> +class MyPageView(View):
마이페이지에 해당하는 api가 이 view 하나일까요?
suggestion과 같이 UserProfileView와 같이 작성하신다면 해당 유저의 프로필을 불러오는 api 뿐만 아니라, 해당 유저의 프로필을 업데이트하는 api도 해당 view class안에서 다른 함수로만 작성해서 활용할 수 있습니다!
```suggestion
class UserProfileView(View):
```

2021-12-02 07:00 UTC, bigfanoftim commented on users/views.py
> +            return JsonResponse({"message" : "SUCCESS", "result" : result})
한 유저에 대한 정보만 리턴하는 api인 것 같습니다. 굳이 리스트를 만들어서 append를 쓸 필요가 없어보입니다!

2021-12-03 08:25 UTC, bigfanoftim requested changes

2021-12-03 08:25 UTC, bigfanoftim commented on users/views.py
>  from core.utils   import login_decorator
불필요하게 너무 많은 공백이 더해진 것 같습니다! 수정해주세요~
```suggestion
import json, bcrypt, jwt

from django.core.exceptions import ValidationError
from django.views           import View
from django.http            import JsonResponse, HttpResponse

from .models      import User
from my_settings  import SECRET_KEY, ALGORITHM
from .validation  import validate_email, validate_phone_number, validate_password
from core.utils   import login_decorator
```

2021-12-03 08:25 UTC, bigfanoftim commented on users/views.py
> +                return JsonResponse({"message" : "INVALID_USER"}, status=401)
```python
except User.DoesNotExist:
    return JsonResponse({"message" : "INVALID_USER"}, status=401)
```
아래에 이러한 예외처리를 해줬는데 user의 존재 여부를 다시 판단할 필요가 있나요? `get` 메소드를 사용했을 때, 어떠한 에러가 발생하는지 다시 한 번 생각해주세요!
```suggestion
```

2021-12-03 12:27 UTC, whytili89 commented on users/views.py
>  from core.utils   import login_decorator
수정하였습니다!

2021-12-03 12:27 UTC, whytili89 commented on users/views.py
> +                return JsonResponse({"message" : "INVALID_USER"}, status=401)
해당부분 삭제 후 MultipleObjectsReturned 에러 추가하였습니다.

2021-12-06 03:48 UTC, whytili89 commented
conflict 해결하였습니다.

2021-12-06 04:54 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-06 04:54 UTC, merged