add:  PostView
wecode-bootcamp-korea/27-1st-branch-backend pull request #18
Opened 2021-12-04 10:49 UTC by whytili89

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상세페이지 포스팅 정보 불러오기 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 하나의 포스팅 정보(제목,생성시간,콘텐츠 등)를 가져오는 PostView 작성
- post_id 입력 시 해당 post_id에 해당하는 정보들을 불러옵니다.

2. get으로 정보를 가져올 때 일어날 수 있는 오류 정의

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 하나의 객체를 get으로 가져오는 방법에 대해 보다 더 자세히 알게되었습니다.

<br />

## :: 기타 질문 및 특이 사항
-

2021-12-04 10:58 UTC, jumyeong33 commented on postings/views.py
> +        except Posting.MultipleObjectsReturned:
이것은 무슨에러를 반환하는 건가요?

2021-12-04 10:59 UTC, whytili89 commented on postings/views.py
> +        except Posting.MultipleObjectsReturned:
MultipleObjectReturned는 get 메서드 사용시 두개 이상의 객체가 존재할 경우 발생합니다!

2021-12-06 07:22 UTC, lordmyshepherd requested changes

2021-12-06 07:22 UTC, lordmyshepherd commented on postings/views.py
> +        except Posting.MultipleObjectsReturned:
지워주세요.

2021-12-07 05:52 UTC, whytili89 commented on postings/views.py
> +        except Posting.MultipleObjectsReturned:
해당 부분 삭제 후 posting에 포함된 태그들이 나오도록 수정하였습니다.

2021-12-07 06:56 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-07 08:44 UTC, whytili89 commented
conflict가 없는 것으로 나오는데 status:conflict해결 요쳥 라벨로 변경되어서 혹시 어떤 점이 문제인지 궁금합니다!

2021-12-07 09:31 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-07 09:31 UTC, merged