Add: app branch_tag 추가
wecode-bootcamp-korea/27-1st-branch-backend pull request #2
Opened 2021-11-30 10:11 UTC by Djangowon

.gitignore 에 tags 라는 이름 포함되어 있어 tags 디렉토리 빠져 있었습니다.
branch_tags 로 이름 수정해서 pr 합니다.

2021-11-30 10:25 UTC, bigfanoftim requested changes

2021-11-30 10:25 UTC, bigfanoftim commented on branch_tags/models.py
> +class User_tag(models.Model):
class 명은 camelCase로 작성해주세요!
```suggestion
class UserTag(models.Model):
```

2021-11-30 10:25 UTC, bigfanoftim commented on branch_tags/models.py
> +class Posting_tag(models.Model):
```suggestion
class PostingTag(models.Model):
```

2021-11-30 10:25 UTC, bigfanoftim commented on branch_tags/models.py
> +        db_table = 'users_tags'
```suggestion
        db_table = 'user_tags'
```

2021-11-30 10:25 UTC, bigfanoftim commented on branch_tags/models.py
> +        db_table = 'postings_tags'
```suggestion
        db_table = 'posting_tags'
```

2021-11-30 10:28 UTC, bigfanoftim requested changes

2021-11-30 10:28 UTC, bigfanoftim commented on branch_tags/models.py
> +    keyword      = models.ForeignKey(Keyword, on_delete=CASCADE)
suggestion과 같이 작성해주시면 이미 models를 import 했었기 때문에 거기서 다시 CASCADE를 import 하지 않아도 됩니다!
```suggestion
    keyword      = models.ForeignKey(Keyword, on_delete=models.CASCADE)
```

2021-11-30 10:28 UTC, bigfanoftim commented on branch_tags/models.py
> +from django.db.models.deletion import CASCADE
CASCADE 관련 리뷰 작성해드렸습니다 확인해주세요~
```suggestion
```

2021-12-01 01:20 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-01 01:21 UTC, merged