add: 회원가입 기능 구현
wecode-bootcamp-korea/27-1st-branch-backend pull request #5
Opened 2021-12-01 07:07 UTC by Djangowon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원가입 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
#### 회원가입 입력 데이터 유효성 검사
- 조건문과 정규식을 이용한 email, phone_number, password 유효성 검사를 진행
- 유효성 검사
email                 - '@' 여부, '.' 여부
password          - 특수문자, 대문자 , 소문자, 숫자 포함 8자리 이상
phone_number - '01' 시작여부, 가운데 숫자 3개, 마지막 숫자 4개

- 유효성 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현
- 회원가입 성공시 201 반환

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2021-12-01 08:02 UTC, lordmyshepherd requested changes

2021-12-01 08:02 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({'message':'INVALID_PASSWORD'}, status=400)
여기서 사용하고 있는 validation은 로그인에서도 사용될 수 있을 것 같습니다. View에 검증 로직을 넣어서 관리하기 보다는 분리해서 모듈화 하는 것이 좋을 것 같습니다. class를 활용해서 validation을 구현해 보시겠어요?

```python
            REGEX_EMAIL = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9_-]+\.[a-zA-Z0-9-.]+$'
            REGEX_PHONE_NUMBER = '^01[016789]{1}-?([0-9]{3,4})-?[0-9]{4}$'
            REGEX_PASSWORD = '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{8,}'

            if not re.match(REGEX_EMAIL, email):
                return JsonResponse({'message': 'INVALID_EMAIL'}, status=400)

            if not re.match(REGEX_PHONE_NUMBER, phone_number):
                return JsonResponse({'message': 'INVALID_PHONE_NUMBER'}, status=400)

            if not re.match(REGEX_PASSWORD, password):
                return JsonResponse({'message':'INVALID_PASSWORD'}, status=400)
```

2021-12-01 09:17 UTC, Djangowon commented on users/views.py
> +                return JsonResponse({'message':'INVALID_PASSWORD'}, status=400)
모듈화 수정완료 했습니다!

2021-12-02 01:51 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-02 01:51 UTC, merged