Feature/user list
wecode-bootcamp-korea/27-1st-branch-backend pull request #9
Opened 2021-12-01 13:58 UTC by jumyeong33

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 작가 리스트 데이터를 메인페이지에 넘겨주기위한 view
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. user list를 받아 모든 정보를 리턴한다. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- django queryset에 대한 이해도 증가

<br />

## :: 기타 질문 및 특이 사항

2021-12-02 01:52 UTC, lordmyshepherd requested changes

2021-12-02 01:52 UTC, lordmyshepherd commented on users/views.py
> +        return JsonResponse({'SUCCESS': result}, status=200)
User List View는 왜 필요한가요?

2021-12-02 04:26 UTC, jumyeong33 commented on users/views.py
> +        return JsonResponse({'SUCCESS': result}, status=200)
메인 페이지에 유저 프로필 목록을 6명 보여주는 리스트가 필요할 것 같아서 추가했습니다. 
프론트 개발자와 미팅결과 태그에 따른 유저리스트 최대 6명을 리턴하는 것으로 결정했습니다 수정하겠습니다
<img width="1421" alt="스크린샷 2021-12-02 오후 1 17 14" src="https://user-images.githubusercontent.com/57386602/144357559-74257d79-e94c-4cba-9274-c98ab6b9d699.png">
.

2021-12-02 05:47 UTC, lordmyshepherd requested changes

2021-12-02 05:47 UTC, lordmyshepherd commented on users/views.py
> +        return JsonResponse({'SUCCESS': result}, status=200)
그렇다면, 아래와 같이 피드백을 드릴 수 있겠습니다.
1. Class명을 UserListView로 수정이 필요할 것 같습니다. 정확히 어떤 목록을 반환하는 class인지 알 수 있겠죠?
2. 전체 유저 중에서도 스타트업 테그가 달린 6명의 유저만 반환해주도록 구현해야겠죠?
-> filter 기능과 offset, limit 기능을 추가해주세요! (RestAPI 설계 방식 참고)

2021-12-03 01:44 UTC, lordmyshepherd requested changes

2021-12-03 01:44 UTC, lordmyshepherd commented on users/views.py
> +            })
이전에 드렸던 피드백이 아직 반영이 안된 것 같아보입니다.
1. Class명 수정 ListView -> UserListView
2. API는 페이지를 기준으로 만들면 안됩니다. 데이터 기준으로 만드셔야 합니다. 
    무슨 얘기냐면, 메인 페이지가 아니라 다른 곳에서는 20개가 필요한 경우가 생길 수 있겠죠?
    이런 경우에 `[:6]` 이렇게 하드코딩 해 놓으면 View를 새로 만들어야되는 문제가 생깁니다.
    
    그렇기 때문에 UserListView가 여러 곳에서 사용될 수 있도록 유연하게 만들어주셔야 합니다.
    filter 기능과 offset, limit 기능을 추가해주세요! (RestAPI 설계 방식 참고)

2021-12-03 05:07 UTC, closed without merging